refactor(react-query-devtools): use `superjson` to display values
TanStack/query pull request #4085
Opened 2022-08-25 16:15 UTC by aboqasem

2022-08-26 09:31 UTC, TkDodo requested changes

2022-08-26 09:31 UTC, TkDodo commented on package.json
> +    "superjson": "^1.9.1",
This needs to be a `dependency` of the `react-query-devtools` package please.

2022-08-26 19:02 UTC, TkDodo commented
not sure that there should be so many changes in package-lock.json, also, builds are failing. I would suggest reverting the changes to packge-lock (restoring what we have in main), then running `npm install` again.

2022-08-26 19:10 UTC, aboqasem commented
I tried and it produces similar result. Which version of `npm` should I use? Currently I have to `npm i --legacy-peer-deps` on `8.18.0`.

2022-08-26 19:14 UTC, TkDodo commented
our `.nvmrc` uses node `v16.14.2`, so please use that

2022-08-26 19:35 UTC, TkDodo approved these changes

2022-09-11 11:52 UTC, TkDodo commented
sorry, I wanted to wait until we merged our beta branch with bundling changes. If you fix the merge conflicts, I'll merge this PR

2022-10-04 11:35 UTC, TkDodo approved these changes

2022-10-04 11:35 UTC, merged

2022-10-04 14:13 UTC, TkDodo commented
yeah, we fixed it immediately. sorry 🙈