docs(community): adding zodios usage and example
TanStack/query pull request #5314
Opened 2023-04-23 19:25 UTC by enyelsequeira

# Changes

I think zodios is a great example that could be included in the `Community Resources`. It is easy to use and all with typesafety in mind.

2023-04-24 07:39 UTC, TkDodo requested changes
you need to add an entry to `config.json`:

https://github.com/TanStack/query/blob/765f6196e900c1dd826b040773fcf97839ca60d0/docs/config.json#L190-L208

2023-04-24 07:39 UTC, TkDodo commented
@ecyrbe FYI :)

2023-04-24 08:20 UTC, enyelsequeira commented
> you need to add an entry to `config.json`:
> 
> https://github.com/TanStack/query/blob/765f6196e900c1dd826b040773fcf97839ca60d0/docs/config.json#L190-L208

Understood it has been added and changed id of .md

2023-04-24 11:40 UTC, ecyrbe commented
Hello, i don't think this is the way to integrate zodios in tanstack query docs.

Because Zodios can change interface, have breaking changes, etc and tanstack query will have a hard time to maintain these docs in sync.

A simple link to some Zodios docs would be enough in my point of view.

What do you think ?

2023-04-24 12:34 UTC, enyelsequeira commented
> Hello, i don't think this is the way to integrate zodios in tanstack query docs.
> 
> Because Zodios can change interface, have breaking changes, etc and tanstack query will have a hard time to maintain these docs in sync.
> 
> A simple link to some Zodios docs would be enough in my point of view.
> 
> What do you think ?

Hey, so I think every resource out there will have breaking changes. When the moment comes someone would just have to update the documentation for it. I think I’ve seen some other pull request updating docs as something changes as well. Just my thoughts though.

2023-04-24 16:40 UTC, ecyrbe reviewed
Some minor typo 😁

2023-04-24 16:40 UTC, ecyrbe commented on docs/config.json
> +              "to": "react/community/zodios-by-ecrybe"
```suggestion
              "to": "react/community/zodios-by-ecyrbe"
```

2023-04-24 16:40 UTC, ecyrbe commented on docs/react/community/zodios.md
> +id: zodios-by-ecrybe
```suggestion
id: zodios-by-ecyrbe
```

2023-04-24 17:26 UTC, enyelsequeira commented on docs/config.json
> +              "to": "react/community/zodios-by-ecrybe"
oops, my mistake 😅, spelling has been fixed :)

2023-05-02 09:58 UTC, TkDodo commented
I've discussed with @ecyrbe and we've decided to go a little different approach: We'll draft one "Awesome React Query Collection" (similar to how [trpc](https://trpc.io/docs/community/awesome-trpc) does it) page where we'll list all community packages with links to docs, github and also when this might be a good fit. This seems better than a separate page for each, with a "quickstart" guide that might get outdated fast

2023-05-02 09:58 UTC, closed without merging