feat(vue-query): support injectable contexts
TanStack/query pull request #5886
Opened 2023-08-19 09:22 UTC by posva

This feature requires Vue 3.3.0, which has been out for a while now. It allows using vue-query APIs in places where it is valid to use them but currently throws an error.

- `hasInjectionContext()`: https://github.com/vuejs/core/pull/8111
- `app.runWithContext()`: https://github.com/vuejs/core/pull/7451

The only thing that I think is left to do is to add extra warnings in some APIs that rely on the Reactivity API (`ref`, `watch`, `onScopeDispose` etc) by checking if there is a current effect scope. I _think_ this was previously achieved by checking for a current instance within the `useQueryClient` which seems to be used in functions relying on those functions. But since it wasn't tested, I didn't add them. Let me know if I should add them.

This change requires vue-demi to also be updated, if the package manager doesn't do it for their users, they shall run an `pnpm update` or similar, they can also install vue-demi and debug with `pnpm why` (or similar).

I can also replicate the PR for the `beta` branch

2023-08-19 20:09 UTC, DamianOsipiuk requested changes
I would prefer to not introduce this in the current v4.x version if it requires other libraries to be updated as well.  
Even though bumping two packages minor version should not be a problem i would prefer to avoid people updating `vue-query` realize that it does not work via compilation errors and then trying to figure out what is wrong.
v5 is in beta already, so i guess it would be more appropriate to introduce this feature there.  
This will have a proper message in `migration guide` and will encourage people to update to the latest version if they need this feature (which is a win-win).

As for 
> The only thing that I think is left to do is to add extra warnings in some APIs that rely on the Reactivity API (ref, watch, onScopeDispose etc) by checking if there is a current effect scope. I think this was previously achieved by checking for a current instance within the useQueryClient which seems to be used in functions relying on those functions. But since it wasn't tested, I didn't add them. Let me know if I should add them.

This is true, but we had an escape hatch in place, where you could provide `queryClient` as a parameter to `useQuery` which will in result skip call to `useQueryClient`.
Now when you mentioned it it seems that if someone would use it without `effectScope()` it would leak. So check for it on top of every composable just before `const client = queryClient || useQueryClient()` would prevent that from happening.

2023-08-20 17:03 UTC, posva commented
> I would prefer to not introduce this in the current v4.x version if it requires other libraries to be updated as well.
Even though bumping two packages minor version should not be a problem i would prefer to avoid people updating vue-query realize that it does not work via compilation errors and then trying to figure out what is wrong.

I understand but for Vue 3.3 users, not being able to use the query client within a navigation guard would be a bug. So you can also see this as a bugfix. In practice, users update multiple libraries at the same time and they should also see the requirement in peer deps.

2023-08-20 17:04 UTC, posva commented on packages/vue-query/src/useQueryClient.ts
>      throw new Error('vue-query hooks can only be used inside setup() function.')
I think splitting makes more sense as one could use the query client independently

2023-08-20 17:12 UTC, posva commented on packages/vue-query/src/useQueryClient.ts
>      throw new Error('vue-query hooks can only be used inside setup() function.')
I split the message and checks. I made it only a warning because it might not be critical in all application (e.g SPA)

2023-08-21 06:52 UTC, Mini-ghost commented
@posva I'm not sure if PR #5703 is a progressive transition option?

2023-08-21 08:35 UTC, posva commented
it should make it work in most cases yes

2023-08-25 21:38 UTC, DamianOsipiuk commented
Build should be fixed with https://github.com/vueuse/vue-demi/pull/241

2023-08-25 21:38 UTC, DamianOsipiuk approved these changes

2023-08-28 08:25 UTC, posva commented
I released a new version of vue-demi 🙂

2023-08-30 08:11 UTC, merged

2023-10-18 15:15 UTC, callumacrae commented
If anyone has issue with getting this to work and comes across this PR / comment, be aware that it doesn't always work like you might think in async functions - if you `await` anything, the injectable context doesn't exist anymore afterwards and the library will throw an error.

I worked around this by getting the query client before my async stuff and then passing it in to my query function:

```ts
  const queryClient = useQueryClient();

  const { isClient } = useCurrentOrg();
  if (!(await isClient())) {
    next('/');
    return;
  }

  const { trial, isTrialEnded } = useTrial({}, queryClient);
```

(where `useTrial` passes `queryClient` through as the second option to `useQuery`)

btw @posva, thanks for adding this! it's super useful :)

2023-10-25 09:54 UTC, escapedcat commented
https://github.com/TanStack/query/discussions/5783 and #5703 brought me here.
So by adding the client as a second param everything works (again) but the warning continues to show up, right?
This helped. Thanks!

2023-10-30 21:33 UTC, MarioC3 commented
Do you think this will work on Nuxt plugins? I'm trying to use `useQueryClient`, but still getting that error.

2024-02-22 15:09 UTC, andredewaard commented
It works but can we get rid of the warning somehow?