refactor(*): Import noop function from utils
TanStack/query pull request #6964
Opened 2024-02-24 10:36 UTC by saul-atomrigs

I found several `noop` function declarations in various files, even though there is already one in `query-core/src/utils`!

So this PR replaces those `noop` functions with the one in `utils`. 

** Let me know if adding them in the `utils` of each directory (`svelte-query`, `react-query`, `solid-query`, `angular-query`, etc.) is a better approach.

2024-02-24 10:41 UTC, TkDodo requested changes

2024-02-24 10:41 UTC, TkDodo commented on packages/query-async-storage-persister/src/asyncThrottle.ts
> +import { noop } from '../../query-core/src/utils'
I don't think we should cross-import between packages, except from their public interface if there is a dependency on that package. One `noop` util function per package should be the way to go, as we wouldn't want to export a public `noop` function from the query core.

2024-02-24 11:20 UTC, saul-atomrigs commented
Thank you for your feedback! 
I have reverted the previous commit and made changes accordingly.

2024-02-24 12:43 UTC, TkDodo commented on packages/angular-query-experimental/src/util/index.ts
why do we have `src/util/index.ts` here but `src/utils.ts` in other places? That's not very consistent

2024-02-24 13:19 UTC, saul-atomrigs commented on packages/angular-query-experimental/src/util/index.ts
Good point. Unlike others, `/angular-query-experimental` had a `util` directory already, so I thought it would be better to use it (instead of having a duplicate `utils` file outside)

2024-02-27 10:32 UTC, saul-atomrigs commented on packages/angular-query-experimental/src/util/index.ts
@TkDodo Should we make a change here? Let me know how to proceed!

2024-02-28 11:52 UTC, TkDodo commented on packages/angular-query-experimental/src/util/index.ts
I think it's fine 👍

2024-02-28 11:52 UTC, TkDodo approved these changes

2024-02-28 11:56 UTC, merged