feat(devtools): add shadowDOMTarget property to react-query-devtool
TanStack/query pull request #7005
Opened 2024-03-01 17:35 UTC by michelleoj

This feature stems from this [conversation](https://github.com/TanStack/query/discussions/6070) with @ardeora

The original issue was that if you rendered the devtools in an component that lives in the shadow dom, the styles would be appended to regular DOM's head tag. Since the shadow DOM encapsulates everything, the devtools shows up unstyled. The fix to this is to pass in the shadow root as a target so that goober library will append the styles to the ShadowRoot element. 
I've gone ahead and added an example and updated the docs. Let me know if there's anything else I'm missing

2024-03-04 20:08 UTC, michelleoj commented
@TkDodo hey there 👋🏾 
I would like some eyes on this when you get the chance 😄 🙏🏾

2024-03-06 16:37 UTC, michelleoj commented
@ardeora any chance I can get some eyes on this soon please?

2024-03-06 17:29 UTC, ardeora commented
Apologies for the delay here. I'll be taking a look at this in an hour or two!

2024-03-07 02:27 UTC, ardeora commented on packages/query-devtools/src/Devtools.tsx
> +const darkStyles = (css) => stylesFactory('dark', css)
```suggestion
const lightStyles = (css: typeof goober['css']) => stylesFactory('light', css)
const darkStyles = (css: (typeof goober)['css']) => stylesFactory('dark', css)
```

Types are erroring could you fix the types like so

2024-03-07 02:27 UTC, ardeora commented on packages/query-devtools/src/Devtools.tsx
> +const stylesFactory = (theme: 'light' | 'dark', css) => {
```suggestion
const stylesFactory = (theme: 'light' | 'dark', css: typeof goober['css']) => {
```

Similarly over here

2024-03-07 17:30 UTC, michelleoj commented
@ardeora added your suggestions and now all tests are passing ✅

2024-03-08 04:40 UTC, ardeora requested changes
These are looking perfect! Thank you for working on this. One other small addition (last one I promise) would be if we can make this feature available in other framework devtools also. You don't need to know Solid, Svelte or Angular. We already have optional props like `styleNonce` in other framework devtools adapter. We can follow the same convention to add an optional shadowDomTarget prop to all other devtools too. Once that is done, I think we are good to merge.

2024-03-11 14:19 UTC, michelleoj commented
@ardeora just added your suggestions and it's ready for another review! 🙏🏾

2024-03-12 02:18 UTC, ardeora approved these changes

2024-03-12 02:19 UTC, merged

2024-03-12 02:20 UTC, ardeora commented
@michelleoj Thank you so much for working on this! Everything looks great and should be included in the next minor version!

2024-03-12 10:39 UTC, michelleoj commented
@ardeora thanks so much for taking the time to review my PR! this is my first time contributing to an open source project so thanks for helping me through it 🎉 ❤️